<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SYNBLRLT-207" name="com.lch.testscripts.TestScripts" tests="10" failures="1" timestamp="19 Apr 2018 08:18:12 GMT" time="22.641" errors="0">
  <testcase name="testMethod" time="4.040" classname="com.lch.testscripts.TestScripts"/>
  <testcase name="testMethod" time="0.385" classname="com.lch.testscripts.TestScripts"/>
  <testcase name="testMethod" time="3.600" classname="com.lch.testscripts.TestScripts"/>
  <testcase name="testMethod" time="3.763" classname="com.lch.testscripts.TestScripts"/>
  <testcase name="testMethod" time="3.667" classname="com.lch.testscripts.TestScripts"/>
  <testcase name="testMethod" time="2.440" classname="com.lch.testscripts.TestScripts"/>
  <testcase name="testMethod" time="0.249" classname="com.lch.testscripts.TestScripts"/>
  <testcase name="testMethod" time="0.244" classname="com.lch.testscripts.TestScripts"/>
  <testcase name="testMethod" time="0.237" classname="com.lch.testscripts.TestScripts"/>
  <testcase name="testMethod" time="4.016" classname="com.lch.testscripts.TestScripts">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [201] but found [200]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [201] but found [200]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.lch.testscripts.TestScripts.testMethod(TestScripts.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
    </failure>
  </testcase> <!-- testMethod -->
</testsuite> <!-- com.lch.testscripts.TestScripts -->
